### ISSUE TITLE
Relative path for cover image

### ISSUE THREAD

**Issue by singhkays** [adityatelange/hugo-PaperMod#13]
From the installation notes I see that the cover image supports absolute path. I'm trying to migrate from another theme where the following relative path for cover image works

`cover = "media/small-cover-spotify.png"`

which **resolves to** `http://localhost:1313/media/small-cover-spotify.png` 
**instead of** `http://localhost:1313/blog/how-spotify-is-killing-the-open-podcast-ecosystem/media/small-cover-spotify.png`

How can I get this working?

**Comment by adityatelange** [comment]
Hey @singhkays, 
I have pushed a commit for this issue
https://github.com/adityatelange/hugo-PaperMod/commit/d8199140e5940f02960196d1220c9a0ce8a23de1

Please let me know if that works fine for you ...

**Comment by singhkays** [comment]
@adityatelange works great now! I'm very excited to see you're making a lot of progress over the last few days on this theme 👏 I'll be making this the main theme on my blog https://www.singhkays.com/. I'll close this issue but post a couple of ideas as feature suggestions here on Github.

**Comment by adityatelange** [comment]
> @adityatelange works great now! I'm very excited to see you're making a lot of progress over the last few days on this theme 👏 I'll be making this the main theme on my blog https://www.singhkays.com/. I'll close this issue but post a couple of ideas as feature suggestions here on Github. 

Thank you for your kind words :)
suggestions are welcome.

**Comment by singhkays** [comment]
@adityatelange Looks like this is still a problem. Here's a live example - https://www.singhkays.com/blog/av1-2019-year-in-review/. The path should be `https://www.singhkays.com/blog/av1-2019-year-in-review/media/av1-2019-year-in-review.png` but instead is the below

Interestingly the actual path to the cover image that is displayed on that page is (_**Note the /./ in the path**_)
`https://www.singhkays.com/blog/av1-2019-year-in-review/./media/av1-2019-year-in-review.png`

```html
<meta property="og:url" content="https://www.singhkays.com/blog/av1-2019-year-in-review/" />
<meta property="og:image" content="https://www.singhkays.com/media/av1-2019-year-in-review.png" />
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://www.singhkays.com/media/av1-2019-year-in-review.png"/>
```

Here's how the cover and images paths are specified in the front-matter

```yaml
cover: 
    image: ./media/av1-2019-year-in-review.png
date: "2020-01-29"
draft: false
images:
- ./media/av1-2019-year-in-review.png
```

**Comment by adityatelange** [comment]
1. I did fix the /./ in url path, let me know if that works fine for all your pages 

2. for the opengraph and twitter, the images param 

```
images:
- ./media/av1-2019-year-in-review.png
```
this won't work as hugo's (opengraph and twitter)'s template doesn't support relative urls, and I cannot fix that

**Comment by singhkays** [comment]
> this won't work as hugo's (opengraph and twitter)'s template doesn't support relative urls, and I cannot fix that

Ah damn! that's disappointing. Looks like there are some fixes scattered on the internet. I'll try these

1. https://discourse.gohugo.io/t/links-for-images-videos-audio-in-internal-templates-twitter-cards-and-opengraph/10464
2. https://discourse.gohugo.io/t/how-to-set-open-graph-image-for-a-specific-page/6700/6
3. https://www.telematika.org/post/adjusting-hugo-internal-open-graph-template/

**Comment by singhkays** [comment]
@adityatelange The first link worked perfectly! I'll close this but you should think about implementing this in the theme by default. I can see the value add of specifying one of the images in the blog post as one of the OG or Twitter card images rather than storing these in a separate folder and then specifying the absolute path.
