### ISSUE TITLE
[Bug]: example site does not work with current versions

### ISSUE THREAD

**Issue by vwegert** [adityatelange/hugo-PaperMod#1699]
### What happened?

I am unable to compile the example site using v0.144.2+extended and the current theme version. 

### Steps to reproduce

1. `git clone https://github.com/adityatelange/hugo-PaperMod.git`
2. `cd hugo-PaperMod`
3. `git checkout exampleSite`
4. `git submodule update --init`
5. `hugo`

### Hugo Version

Hugo >= 0.125.7 (Recommended - Minimum version required for PaperMod)

### PaperMod Version

current head / 045c08496d61b1b3f9c79e69e7d3d243a526d8f3

### Relevant log output

```shell
ERROR deprecated: site config key paginate was deprecated in Hugo v0.128.0 and subsequently removed. Use pagination.pagerSize instead.
WARN  deprecated: site config key services.twitter.disableInlineCSS was deprecated in Hugo v0.141.0 and will be removed in a future release. Use services.x.disableInlineCSS instead.
Start building sites … 
hugo v0.144.2+extended linux/amd64 BuildDate=unknown VendorInfo=gentoo:0.144.2

ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and subsequently removed. Implement taxonomy 'social' or use .Site.Params.Social instead.
WARN  The "gist" shortcode was deprecated in v0.143.0 and will be removed in a future release. See https://gohugo.io/shortcodes/gist for instructions to create a replacement.
WARN  The "twitter", "tweet", and "twitter_simple" shortcodes were deprecated in v0.142.0 and will be removed in a future release. Please use the "x" shortcode instead.
Total in 254 ms
Error: error building site: logged 2 error(s)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Justin-De-Sio** [comment]
I encountered the same issue.

**Comment by hemendrarajawat** [comment]
Encountering the '.Site.Social was deprecated' in an existing website I had. When this is planned to be deployed?

```
ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and subsequently removed. Implement taxonomy 'social' or use .Site.Params.Social instead.
Built in 57 ms
Error: error building site: logged 1 error(s)
```

**Comment by totoroot** [comment]
@hemendrarajawat You can take a look at my PR in #1701, check out the feature branch and rebuild your site.
It should fix the issue you are seeing.

**Comment by trafotin** [comment]
The fix is you need to change in the config.yml where it says `twitter` to `x`. This is because of an upstream change to Hugo. https://gohugo.io/shortcodes/x/

**Comment by ccoles146** [comment]
@totoroot I tried out your repository and it was almost there apart from two more points:
- in `rich-content.md` file there is still a reference to a twitter shortcode that caused the build to fail. I just deleted it and it works because I don't know enough yet to convert it to x.
- in config.yml the `twitter:` and `disableInlineCSS: true` lines still exist and need to be deleted or replaced.
Other than that it now works.  Thanks.

**Comment by ccoles146** [comment]
Actually I have another point where this does not work: the reason I downloaded the example site was to try to understand the Post pinning or ordering. I think it has changed somehow.  PaperMod example site has what appears to be a fixed order of posts. Whereas with the latest version of Hugo using weights does not seem to work anymore. I think it takes folders alphabetically and then applies the weights within each folder, although I can't really work it out.

**Comment by ccoles146** [comment]
I'm embarrassed that it took so long to find the cause. Some of the posts in the example site have been change to draft and then the weight will not work. By changing the draft status to `false` in the following files, or simply deleting the line then the example site will look the same as it is supposed to:
- papermod-faq.md
- papermod-icons.md
- papermod-variables.md

**Comment by adityatelange** [comment]
This is fixed
